module.exports = {
    dok:'dok',
    journal:'/raamatupidamine/journal',
    arv:'/raamatupidamine/arv',
    smk:'/raamatupidamine/smk',
    vmk:'/raamatupidamine/vmk',
    sorder:'/raamatupidamine/sorder',
    vorder:'/raamatupidamine/vorder',
    asutused:'/libs/libraries/asutused',
    kontod:'/libs/libraries/kontod',
    dokprops: '/libs/libraries/dokprops',
    users: '/libs/libraries/users',
    nomenclature: '/libs/libraries/nomenclature',
    document: '/libs/libraries/document',
    aa: '/libs/libraries/aa',
    arvedsisse: '/libs/libraries/arvedsisse',
    tunnus: '/libs/libraries/tunnus',
    project: '/libs/libraries/project',
    kassa: '/libs/libraries/kassa',
    kontoandmik: '/aruanned/raamatupidamine/kontoandmik'
}